name: PR checks
on:
  - pull_request
  - merge_group

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - run: echo "RUST_TOOLCHAIN=$(just rust-version)" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: debug-build
      - name: Test
        run: just test

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - run: |
          echo "RUST_TOOLCHAIN=$(just rust-version)" >> $GITHUB_ENV
          echo "RUST_TOOLCHAIN_NIGHTLY=$(just rust-nightly-version)" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_NIGHTLY }}
          components: rustfmt
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: debug-build
      - name: Lint
        run: just lint "strict"
